### ISSUE TITLE
Tag Rooms Error

### ISSUE THREAD

**Issue by dezindzer** [revitron/revitron#3]
Hi, 

I like the idea, but there seems to be an error.
I got past choosing the desired tag but after that, I get this:

![image](https://user-images.githubusercontent.com/77564/151353918-d0b86e25-bd5b-45ff-b091-f4c6977937be.png)

additional info:

Revit 2020.2.7
The latest version of your extension is used (idk the build)

**Comment by marcantondahmen** [comment]
Hi, thanks for reporting this. I was looking into it but couldn't reproduce that error. Is that the only function that returns such error? After some quick research I learned that it seems to be more a system issue related to some kind of memory leak that was introduced by some 3rd party software or even a Windows update. 

As a first try you can reinstall pyRevit and Revitron or test it on another machine.

Maybe you can also try to open an issue in the pyRevit repo since that is actually the runtime that is used to run the Python scripts.

**Comment by dezindzer** [comment]
Hi,
Sorry for the late reply.
I was testing this on other PCs and could not replicate the issue.
I also had another issue with another AddIn.
Could be something wrong with the PC.
Anyway, thanks for the trouble.
